import Head from 'next/head'
import Stupid from "../components/stupid";

export default function Hair() {
  return (
      <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      </main>
    </div>
  )
}
